openapi: 3.0.3
info:
  title: LicenseService API
  version: 1.0.0
  description: |
    API specification for the LicenseService of the e-shop application.
    Generates and manages digital licenses for purchased products.
    Provides admin endpoints to manage license templates and view generated licenses.

servers:
  - url: https://licenseservice.yourshop.com
    description: Production server
  - url: https://licenseservice.staging.yourshop.com
    description: Staging server

paths:
  /license-templates:
    get:
      summary: List all license templates
      operationId: listLicenseTemplates
      tags:
        - License Templates
      security:
        - bearerAuth: []
        - adminAuth: []
      responses:
        '200':
          description: License templates retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseTemplateListResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new license template (admin only)
      operationId: createLicenseTemplate
      tags:
        - License Templates
      security:
        - bearerAuth: []
        - adminAuth: []
      requestBody:
        description: License template data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLicenseTemplateRequest'
      responses:
        '201':
          description: License template created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseTemplateResponse'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /license-templates/{productId}:
    get:
      summary: Get license template by product ID
      operationId: getLicenseTemplateByProductId
      tags:
        - License Templates
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/ProductIdPathParam'
      responses:
        '200':
          description: License template retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseTemplateResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - License template does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Create or update license template for a product
      operationId: updateLicenseTemplate
      tags:
        - License Templates
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/ProductIdPathParam'
      requestBody:
        description: License template data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLicenseTemplateRequest'
      responses:
        '200':
          description: License template updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseTemplateResponse'
        '201':
          description: License template created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseTemplateResponse'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


    delete:
      summary: Delete a license template (admin only)
      operationId: deleteLicenseTemplate
      tags:
        - License Templates
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/ProductIdPathParam'
      responses:
        '200':
          description: License template deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteLicenseTemplateResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - License template does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /licenses:
    get:
      summary: List all generated licenses
      operationId: listLicenses
      tags:
        - Licenses
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/PageQueryParam'
        - $ref: '#/components/parameters/LimitQueryParam'
        - $ref: '#/components/parameters/UserIdQueryParam'
        - $ref: '#/components/parameters/ProductIdQueryParam'
        - $ref: '#/components/parameters/SortQueryParam'
      responses:
        '200':
          description: Licenses retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseListResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /licenses/{serialNumber}:
    get:
      summary: Get license by serial number
      operationId: getLicenseBySerialNumber
      tags:
        - Licenses
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/SerialNumberPathParam'
      responses:
        '200':
          description: License retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - License does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    adminAuth:
      type: apiKey
      in: header
      name: X-Admin-Token
      description: Token for admin access

  parameters:
    ProductIdPathParam:
      name: productId
      in: path
      description: UUID of the product
      required: true
      schema:
        type: string
        format: uuid
        example: 321e4567-e89b-12d3-a456-426614174000

    SerialNumberPathParam:
      name: serialNumber
      in: path
      description: Serial number of the license
      required: true
      schema:
        type: string
        format: uuid
        example: 456e7890-e89b-12d3-a456-426614174003

    PageQueryParam:
      name: page
      in: query
      description: Page number for pagination (default is 1)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1

    LimitQueryParam:
      name: limit
      in: query
      description: Number of items per page (default is 10)
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10

    UserIdQueryParam:
      name: userId
      in: query
      description: Filter licenses by user ID
      required: false
      schema:
        type: string
        format: uuid
        example: 456e7890-e89b-12d3-a456-426614174002

    ProductIdQueryParam:
      name: productId
      in: query
      description: Filter licenses by product ID
      required: false
      schema:
        type: string
        format: uuid
        example: 321e4567-e89b-12d3-a456-426614174000

    SortQueryParam:
      name: sort
      in: query
      description: Sort order (e.g., 'dateAsc', 'dateDesc')
      required: false
      schema:
        type: string
        enum:
          - dateAsc
          - dateDesc
        example: 'dateDesc'

  schemas:
    LicenseTemplate:
      type: object
      properties:
        productId:
          type: string
          format: uuid
          example: 321e4567-e89b-12d3-a456-426614174000
        licenseDuration:
          type: integer
          description: Duration of the license in days (0 for perpetual)
          example: 365
        createdAt:
          type: string
          format: date-time
          example: '2023-10-15T10:00:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-10-16T12:00:00Z'
      required:
        - productId
        - licenseDuration
        - createdAt
        - updatedAt
      additionalProperties: false

    LicenseTemplateResponse:
      allOf:
        - $ref: '#/components/schemas/LicenseTemplate'

    LicenseTemplateListResponse:
      type: object
      properties:
        licenseTemplates:
          type: array
          items:
            $ref: '#/components/schemas/LicenseTemplate'
      additionalProperties: false

    UpdateLicenseTemplateRequest:
      type: object
      required:
        - licenseDuration
      properties:
        licenseDuration:
          type: integer
          description: Duration of the license in days (0 for perpetual)
          example: 365
      additionalProperties: false

    License:
      type: object
      properties:
        serialNumber:
          type: string
          format: uuid
          example: 456e7890-e89b-12d3-a456-426614174003
        userId:
          type: string
          format: uuid
          example: 456e7890-e89b-12d3-a456-426614174002
        productId:
          type: string
          format: uuid
          example: 321e4567-e89b-12d3-a456-426614174000
        licenseDuration:
          type: integer
          description: Duration of the license in days (0 for perpetual)
          example: 365
        issuedAt:
          type: string
          format: date-time
          example: '2023-10-17T09:00:00Z'
        expiresAt:
          type: string
          format: date-time
          example: '2024-10-17T09:00:00Z'
        status:
          type: string
          enum:
            - active
            - expired
            - revoked
          example: 'active'
      required:
        - serialNumber
        - userId
        - productId
        - licenseDuration
        - issuedAt
        - status
      additionalProperties: false

    CreateLicenseTemplateRequest:
      type: object
      required:
        - productId
        - licenseDuration
      properties:
        productId:
          type: string
          format: uuid
          description: ID of the product for which the license template is created
          example: 321e4567-e89b-12d3-a456-426614174000
        licenseDuration:
          type: integer
          description: Duration of the license in days (0 for perpetual)
          example: 365
      additionalProperties: false

    LicenseResponse:
      allOf:
        - $ref: '#/components/schemas/License'

    LicenseListResponse:
      type: object
      properties:
        licenses:
          type: array
          items:
            $ref: '#/components/schemas/License'
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
              example: 1
            totalPages:
              type: integer
              example: 5
            totalItems:
              type: integer
              example: 50
            limit:
              type: integer
              example: 10
          additionalProperties: false
      additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: 'Invalid input data.'
        details:
          type: string
          example: 'License duration must be a non-negative integer.'
      additionalProperties: false

    DeleteLicenseTemplateResponse:
      type: object
      properties:
        message:
          type: string
          example: "License template deleted successfully."
      required:
        - message
      additionalProperties: false

security:
  - bearerAuth: []

tags:
  - name: License Templates
    description: Endpoints related to managing license templates.
  - name: Licenses
    description: Endpoints related to viewing generated licenses.
