micronaut:
  application:
    name: eh-ma-micronaut-apigateway
  server:
    port: 8080
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
  http:
    services:
      authClient:
        url: http://localhost:8081
      userClient:
        url: http://localhost:8082
      productClient:
        url: http://localhost:8083
      cartClient:
        url: http://localhost:8084
      orderClient:
        url: http://localhost:8085
      paymentClient:
        url: http://localhost:8086
      licenseClient:
        url: http://localhost:8087
      notificationClient:
        url: http://localhost:8088
      trackingClient:
        url: http://localhost:8089

context-path: /