micronaut:
  application:
    name: eh-ma-micronaut-userservice
  server:
    port: 8082
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
kafka:
  bootstrap:
    servers: localhost:29092

mongodb:
  uri: mongodb://localhost:27017/eh-ma-micronaut-userservice-db
  uuid-representation: standard