openapi: 3.0.3
info:
  title: PaymentService API
  version: 1.0.0
  description: |
    API specification for the PaymentService of the e-shop application.
    Manages payment methods and processes payments as part of the microservice choreography.
    Provides endpoints for users to retrieve available payment methods and admin endpoints to manage payment methods.

servers:
  - url: https://paymentservice.yourshop.com
    description: Production server
  - url: https://paymentservice.staging.yourshop.com
    description: Staging server

paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Authservice health response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /payment-methods:
    get:
      summary: Get a list of available payment methods
      operationId: getPaymentMethods
      tags:
        - Payment Methods
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Payment methods retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodListResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new payment method (admin only)
      operationId: createPaymentMethod
      tags:
        - Payment Methods
      security:
        - bearerAuth: []
        - adminAuth: []
      requestBody:
        description: Payment method data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentMethodRequest'
      responses:
        '201':
          description: Payment method created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payment-methods/{id}:
    get:
      summary: Get details of a payment method (admin only)
      operationId: getPaymentMethodById
      tags:
        - Payment Methods
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/PaymentMethodIdPathParam'
      responses:
        '200':
          description: Payment method retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodDetailedResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - Payment method does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update a payment method (admin only)
      operationId: updatePaymentMethod
      tags:
        - Payment Methods
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/PaymentMethodIdPathParam'
      requestBody:
        description: Updated payment method data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePaymentMethodRequest'
      responses:
        '200':
          description: Payment method updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodDetailedResponse'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - Payment method does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a payment method (admin only)
      operationId: deletePaymentMethod
      tags:
        - Payment Methods
      security:
        - bearerAuth: []
        - adminAuth: []
      parameters:
        - $ref: '#/components/parameters/PaymentMethodIdPathParam'
      responses:
        '200':
          description: Payment method deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePaymentMethodResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Not allowed to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - Payment method does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    adminAuth:
      type: apiKey
      in: header
      name: X-Admin-Token
      description: Token for admin access

  parameters:
    PaymentMethodIdPathParam:
      name: id
      in: path
      description: UUID of the payment method
      required: true
      schema:
        type: string
        format: uuid
        example: 987e6543-e89b-12d3-a456-426614174004

  schemas:
    PaymentMethod:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 987e6543-e89b-12d3-a456-426614174004
        selector:
          type: string
          example: "eh-ma-payment-method-paypal"
        name:
          type: string
          example: "Credit Card"
        description:
          type: string
          example: "Pay using Visa, MasterCard, or American Express."
        active:
          type: boolean
          example: true
        iconUrl:
          type: string
          example: "https://yourshop.com/images/payment-icons/credit-card.png"
        paymentGatewayUrl:
          type: string
          example: "https://example.paymentprovider.com/payments"
        merchantId:
          type: string
          example: "eh-ma-payment-merchantId-paypal"

    PaymentMethodResponse:
      allOf:
        - $ref: '#/components/schemas/PaymentMethod'

    PaymentMethodListResponse:
      type: object
      properties:
        paymentMethods:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethod'

    CreatePaymentMethodRequest:
      type: object
      properties:
        name:
          type: string
          example: "PayPal"
        selector:
          type: string
          example: "eh-ma-payment-method-paypal"
        description:
          type: string
          example: "Pay securely using your PayPal account."
        active:
          type: boolean
          example: true
        iconUrl:
          type: string
          example: "https://yourshop.com/images/payment-icons/paypal.png"
        paymentGatewayUrl:
          type: string
          example: "https://example.paymentprovider.com/payments"
        merchantId:
          type: string
          example: "eh-ma-payment-merchantId-paypal"
        merchantSecret:
          type: string
          example: "eh-ma-payment-merchantSecret-paypal"



    UpdatePaymentMethodRequest:
      type: object
      properties:
        name:
          type: string
          example: "PayPal"
        selector:
          type: string
          example: "eh-ma-payment-method-paypal"
        description:
          type: string
          example: "Pay securely using your PayPal account."
        active:
          type: boolean
          example: true
        iconUrl:
          type: string
          example: "https://yourshop.com/images/payment-icons/paypal.png"
        paymentGatewayUrl:
          type: string
          example: "https://example.paymentprovider.com/payments"
        merchantId:
          type: string
          example: "eh-ma-payment-merchantId-paypal"
        merchantSecret:
          type: string
          example: "eh-ma-payment-merchantSecret-paypal"

    PaymentMethodDetailedResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "987e6543-e89b-12d3-a456-426614174004"
        selector:
          type: string
          example: "eh-ma-payment-method-paypal"
        name:
          type: string
          example: "PayPal"
        description:
          type: string
          example: "Pay securely using your PayPal account."
        active:
          type: boolean
          example: true
        iconUrl:
          type: string
          example: "https://yourshop.com/images/payment-icons/paypal.png"
        paymentGatewayUrl:
          type: string
          example: "https://example.paymentprovider.com/payments"
        merchantId:
          type: string
          example: "eh-ma-payment-merchantId-paypal"
        merchantSecret:
          type: string
          example: "eh-ma-payment-merchantSecret-paypal"
        createdAt:
          type: string
          format: date-time
          example: "2024-11-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-11-10T18:00:00Z"

    DeletePaymentMethodResponse:
      type: object
      properties:
        message:
          type: string
          example: "Payment method deleted successfully."
      required:
        - message

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid input data."
        details:
          type: string
          example: "The name field is required."

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Access token expiry time in seconds
          example: "Credentials updated successfuly"

security:
  - bearerAuth: []

tags:
  - name: Payment Methods
    description: Endpoints related to managing payment methods.
