micronaut:
  application:
    name: eh-ma-micronaut-authservice
  server:
    port: 8081
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

context-path: /

kafka:
  bootstrap:
    servers: localhost:29092

mongodb:
  uri: mongodb://localhost:27017/eh-ma-micronaut-authservice-db
  uuid-representation: standard
